<?xml version="1.0"?>
<robot name="mybot_macros" xmlns:xacro="http://www.ros.org/wiki/xacro">
        <!-- Put here the robot description -->

<!-- - - - - - - - - - - -->
<!-- HELPER EXPRESSIONS  -->
<!-- - - - - - - - - - - -->
  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertia ixx="${m * (3 * r * r + h * h) / 12}" ixy="0" ixz="0"
      iyy="${m * (3 * r * r + h * h) / 12}" iyz="0"
      izz="${m * r * r / 2}"
    />
  </xacro:macro>

  <xacro:macro name="box_inertia" params="m x y z">
    <inertia ixx="${m * (y * y + z * z) / 12}" ixy="0" ixz="0"
      iyy="${m * (x * x + z * z) / 12}" iyz="0"
      izz="${m * (x * x + z * z) / 12}"
    />
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
    <inertia ixx="${2 * m * r * r / 5}" ixy="0" ixz="0"
      iyy="${2 * m * r * r / 5}" iyz="0"
      izz="${2 * m * r * r / 5}"
    />
  </xacro:macro>

<!-- - - - - - - - - - - -->
<!--     SERVO MOTOR     -->
<!-- - - - - - - - - - - -->
<macro name="servo" params="ln x y z">

<link name="${ln}">
  <visual>
    <origin rpy="0 0 0" xyz="${x} ${y} ${z}"/>
    <geometry>
      <box size="${servoLength} ${servoHeight} ${servoWidth}" />
    </geometry>
    <material name="green"/>
  </visual>
  <collision>
    <origin rpy="0 0 0" xyz="${x} ${y} ${z}"/>
    <geometry>
      <box size="${servoLength} ${servoHeight} ${servoWidth}" />
    </geometry>
  </collision>
  <visual>
    <origin rpy="0 0 0" xyz="${x+servoLength/2-0.010} ${y} ${z+servoWidth/2+servoAxisLength/2}"/>
    <geometry>
      <cylinder radius="${servoAxisRadius}" length="${servoAxisLength}"/>
    </geometry>
    <material name="green"/>
  </visual>
  <inertial>
    <origin rpy="0 0 0" xyz="${x} ${y} ${z}"/>
    <mass value="0.05"/>
    <box_inertia m="0.05" x="${servoLength}" y="${servoHeight}" z="${servoWidth}"/>
  </inertial>
</link>

<!-- A "transmission" defines the relation between and actuator and a joint. 
     See http://wiki.ros.org/urdf/XML/Transmission-->
<transmission name="${ln}_trans">
	<type>transmission_interface/SimpleTransmission</type>
	<joint name="${ln}_joint">
		<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
	</joint>
	<actuator name="${ln}_motor">
		<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		<mechanicalReduction>100</mechanicalReduction>
	</actuator>
</transmission>

</macro>

<!-- - - - - - - - - - - -->
<!--      WHEELS         -->
<!-- - - - - - - - - - - -->
<macro name="wheel" params="lr tY">

<link name="${lr}_wheel">
  <collision>
    <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
    <geometry>
      <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
    </geometry>
  </collision>

  <visual>
    <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
    <geometry>
      <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
    </geometry>
    <material name="black"/>
  </visual>

  <inertial>
    <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
    <mass value="${wheelMass}"/>
    <cylinder_inertia m="${wheelMass}" r="${wheelRadius}" h="${wheelWidth}"/>
  </inertial>
</link>

<!-- Define friction characteristics -->
<gazebo reference="${lr}_wheel">
  <mu1 value="1.0"/>
  <mu2 value="1.0"/>
  <kp  value="10000000.0" />
  <kd  value="1.0" />
  <fdir1 value="1 0 0"/>
  <material>Gazebo/Black</material>
</gazebo>


<joint name="${lr}_wheel_hinge" type="continuous">
  <parent link="chassis"/>
  <child link="${lr}_wheel"/>
  <origin xyz="${chassisRadius-wheelPos} ${tY*wheelWidth/2+tY*chassisRadius} ${wheelRadius-chassisHeight/2}" rpy="0 0 0" />
  <axis xyz="0 1 0" rpy="0 0 0" />
  <limit effort="100" velocity="100"/>
  <joint_properties damping="0.0" friction="0.0"/>
</joint>


<transmission name="${lr}_trans">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="${lr}_wheel_hinge">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
</joint>
  <actuator name="${lr}Motor">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    <mechanicalReduction>100</mechanicalReduction>
  </actuator>
</transmission>


</macro>

</robot>
