<?xml version="1.0"?>
<robot name="mybot_macros" xmlns:xacro="http://www.ros.org/wiki/xacro">
        <!-- Put here the robot description -->

<!-- - - - - - - - - - - -->
<!-- HELPER EXPRESSIONS  -->
<!-- - - - - - - - - - - -->
  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertia ixx="${m * (3 * r * r + h * h) / 12}" ixy="0" ixz="0"
      iyy="${m * (3 * r * r + h * h) / 12}" iyz="0"
      izz="${m * r * r / 2}"
    />
  </xacro:macro>

  <xacro:macro name="box_inertia" params="m x y z">
    <inertia ixx="${m * (y * y + z * z) / 12}" ixy="0" ixz="0"
      iyy="${m * (x * x + z * z) / 12}" iyz="0"
      izz="${m * (x * x + z * z) / 12}"
    />
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
    <inertia ixx="${2 * m * r * r / 5}" ixy="0" ixz="0"
      iyy="${2 * m * r * r / 5}" iyz="0"
      izz="${2 * m * r * r / 5}"
    />
  </xacro:macro>



<!-- - - - - - - - - - - -->
<!--      WHEELS         -->
<!-- - - - - - - - - - - -->
<xacro:macro name="wheel" params="lr tY">

<link name="${lr}_wheel">
  <visual>
    <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
    <geometry>
      <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
    </geometry>
    <material name="black"/>
  </visual>
</link>

<joint name="${lr}_wheel_hinge" type="continuous">
  <parent link="level0"/>
  <child link="${lr}_wheel"/>
  <origin xyz="${floor0Length/2-wheelXOffset} ${tY*wheelWidth/2+tY*floor0Width/2} ${-wheelFloor0Offset-floor0Heigth/2}" rpy="0 0 0" />
  <axis xyz="0 1 0" rpy="0 0 0" />
  <limit effort="100" velocity="100"/>
  <joint_properties damping="0.0" friction="0.0"/>
</joint>


</xacro:macro>

<!-- - - - - - - - - - - -->
<!--      Motors         -->
<!-- - - - - - - - - - - -->
<xacro:macro name="motor" params="lr tY">

<link name="${lr}_motor">
  <visual>
    <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
    <geometry>
      <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
    </geometry>
    <material name="black"/>
  </visual>
</link>


</xacro:macro>
</robot>
