<?xml version="1.0"?>
<robot name="twirtee" xmlns:xacro="http://www.ros.org/wiki/xacro">
	
<!-- ================== -->	
<!-- (C) Eric JENN 2019 -->
<!-- ================== -->
<!-- To generate the URDF: xacro twirtee.xacro > twirtee.urdf -->
<!-- Constants -->

  <xacro:property name="PI" value="3.1415926535897931"/>
  
<!-- Modeling parameters -->
<!-- [TODO] use actual values -->
  
  <xacro:property name="floor0Length" 	value="0.30"/>
  <xacro:property name="floor0Width" 	value="0.20"/>
  <xacro:property name="floor0Heigth" 	value="0.003"/>
  <xacro:property name="floor0Mass" 	value="1"/>

  <xacro:property name="spacerRadius" 	value="0.002"/>
  <xacro:property name="spacer01Width" 	value="0.060"/>
  <xacro:property name="spacer01Mass" 	value="1"/>
   
  <xacro:property name="floor1Length" 	value="0.300"/>
  <xacro:property name="floor1Width" 	value="0.200"/>
  <xacro:property name="floor1Heigth" 	value="0.003"/>
  <xacro:property name="floor1Mass" 	value="1"/>

  <xacro:property name="spacer12Width" 	value="0.050"/>
  <xacro:property name="spacer12Mass" 	value="1"/>
  
  <xacro:property name="floor2Length" 	value="0.30"/>
  <xacro:property name="floor2Width" 	value="0.20"/>
  <xacro:property name="floor2Heigth" 	value="0.003"/>
  <xacro:property name="floor2Mass" 	value="1"/>

  <xacro:property name="casterRadius" 	value="0.1"/>
  <xacro:property name="casterMass" 	value="5"/>

  <xacro:property name="wheelWidth" 	value="0.010"/>
  <xacro:property name="wheelRadius" 	value="0.032"/>
  <xacro:property name="wheelMass" 		value="5"/>

  <xacro:property name="wheelExcen" 	value="0.007"/>

  <xacro:property name="wheelFixtOffset" 	value="0.030"/>
  <xacro:property name="wheelFloor0Offset" 	value="${wheelFixtOffset+motorFixtHHeigth}"/>
  <xacro:property name="wheelXOffset" 	value="0.05"/>

  <xacro:property name="motorAxisWidth" 	value="0.0045"/>
  <xacro:property name="motorAxisRadius" 	value="0.003"/>
  <xacro:property name="motorAxisMass" 		value="5"/>

  <xacro:property name="motorWidth" 	value="0.0445"/>
  <xacro:property name="motorRadius" 	value="0.0185"/>
  <xacro:property name="motorMass" 		value="5"/>
  


  <xacro:property name="motorFixtVLength" 	value="0.30"/>
  <xacro:property name="motorFixtVWidth" 	value="0.20"/>
  <xacro:property name="motorFixtVHeigth" 	value="0.003"/>
  <xacro:property name="motorFixtVMass" 	value="1"/>
  
  <xacro:property name="motorFixtHLength" 	value="0.30"/>
  <xacro:property name="motorFixtHWidth" 	value="0.20"/>
  <xacro:property name="motorFixtHHeigth" 	value="0.003"/>
  <xacro:property name="motorFixtHMass" 	value="1"/>

  <xacro:property name="cameraSize" 	value="0.02"/>
  <xacro:property name="cameraMass" 	value="0.5"/>


  <xacro:include filename="$(find twirtee_description)/urdf/materials.xacro" />
  <xacro:include filename="$(find twirtee_description)/urdf/macros.xacro" />

<!-- =========================== -->
<!-- Links and joints definition -->
<!-- =========================== -->

  <link name="footprint" />

<!-- Level 0 -->

  <joint name="base_joint" type="fixed">
    <parent link="footprint"/>
    <child link="level0"/>
      <origin xyz="0 0 ${wheelRadius+wheelFloor0Offset+floor0Heigth/2}" rpy="0 0 0" />
  </joint>

  <link name="level0">
    <visual>
      <geometry>
		<box size="${floor0Length} ${floor0Width} ${floor0Heigth}" />
	    <cylinder radius="${spacerRadius}" length="${spacer01Width}"/>
      </geometry>
    </visual>
  </link>

<!-- Level 1 -->

  <joint name="l0l1_joint" type="fixed">
    <parent link="level0"/>
    <child link="level1"/>
	<origin xyz=" 0.0 0.0 ${spacer01Width+floor1Heigth/2}" rpy="0 0 0" />    
  </joint>

  <link name="level1">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
		<box size="${floor1Length} ${floor1Width} ${floor1Heigth}" />
      </geometry>
    </visual>
  </link>

<!-- Level 2 -->

  <joint name="l1l2_joint" type="fixed">
    <parent link="level1"/>
    <child link="level2"/>
	<origin xyz=" 0.0 0.0 ${spacer12Width+floor1Heigth/2}" rpy="0 0 0" />    
  </joint>
    
  <link name="level2">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
		<box size="${floor2Length} ${floor2Width} ${floor2Heigth}" />
      </geometry>
    </visual>
  </link>
      
<!-- ========================== -->
<!--          WHEELS            -->
<!-- ========================== -->

<wheel lr="left" tY="1"/>
<wheel lr="right" tY="-1"/>

<!-- ========================== -->
<!--          MOTORS            -->
<!-- ========================== -->


<!-- ========================== -->
<!--          CAMERA            -->
<!-- ========================== -->

<!-- ========================== -->
<!--          IMU            -->
<!-- ========================== -->


<!-- ========================= -->
<!--           LIDAR           -->
<!-- ========================= -->


</robot>
