<?xml version="1.0"?>
<robot name="twirtee" xmlns:xacro="http://www.ros.org/wiki/xacro">
	
<!-- ================== -->	
<!-- (C) Eric JENN 2019 -->
<!-- ================== -->

<!-- Constants -->

  <xacro:property name="PI" value="3.1415926535897931"/>
  
<!-- Modeling parameters -->
<!-- [TODO] use actual values -->
  
  <xacro:property name="chassisHeight" 	value="0.5"/>
  <xacro:property name="chassisRadius" 	value="0.2"/>
  <xacro:property name="chassisMass" 	value="50"/>

  <xacro:property name="casterRadius" 	value="0.1"/>
  <xacro:property name="casterMass" 	value="5"/>

  <xacro:property name="wheelWidth" 	value="0.005"/>
  <xacro:property name="wheelRadius" 	value="1.82"/>
  <xacro:property name="wheelPos" 		value="0.05"/>
  <xacro:property name="wheelMass" 		value="5"/>

  <xacro:property name="fingerLength" 	value="0.05"/>
  <xacro:property name="fingerRadius" 	value="0.001"/>
  <xacro:property name="fingerWeight" 	value="0.01"/>

  <xacro:property name="servoMass" 		value="0.05"/>
  <xacro:property name="servoHeight" 	value="0.02"/>
  <xacro:property name="servoLength" 	value="0.04"/>
  <xacro:property name="servoWidth" 	value="0.036"/>
  <xacro:property name="servoAxisPos" 	value="0.01"/>
  <xacro:property name="servoAxisRadius" value="0.001"/>
  <xacro:property name="servoAxisLength" value="0.008"/>

  <xacro:property name="cameraSize" 	value="0.02"/>
  <xacro:property name="cameraMass" 	value="0.5"/>

  <xacro:include filename="$(find twirtee_description)/urdf/twirtee.gazebo" />
  <xacro:include filename="$(find twirtee_description)/urdf/materials.xacro" />
  <xacro:include filename="$(find twirtee_description)/urdf/macros.xacro" />

<!-- =========================== -->
<!-- Links and joints definition -->
<!-- =========================== -->

  <link name="footprint" />

<!-- Robot's base -->

  <joint name="base_joint" type="fixed">
    <parent link="footprint"/>
    <child link="chassis"/>
  </joint>

  <link name="chassis">
    <collision>
      <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0" />
      <geometry>
	<cylinder radius="${chassisRadius}" length="${chassisHeight}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
      <geometry>
	<cylinder radius="${chassisRadius}" length="${chassisHeight}"/>
      </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
      <mass value="${chassisMass}"/>
      <cylinder_inertia m="${chassisMass}" r="${chassisRadius}" h="${chassisHeight}"/>
    </inertial>
  </link>

<joint name="fixed" type="fixed">
  <parent link="chassis"/>
  <child link="caster_wheel"/>
</joint>

<link name="caster_wheel">
  <collision>
    <origin xyz="${casterRadius-chassisRadius} 0 ${casterRadius-chassisHeight/2}" rpy="0 0 0"/>
    <geometry>
      <sphere radius="${casterRadius}"/>
    </geometry>
  </collision>
  
  <visual>
    <origin xyz="${casterRadius-chassisRadius} 0 ${casterRadius-chassisHeight/2}" rpy="0 0 0"/>
    <geometry>
      <sphere radius="${casterRadius}"/>
    </geometry>
    <material name="red"/>
  </visual>

  <inertial>
    <origin xyz="${casterRadius-chassisRadius} 0 ${-casterRadius-chassisHeight/2}" rpy="0 0 0"/>
    <mass value="${casterMass}"/>
    <sphere_inertia m="${casterMass}" r="${casterRadius}"/>
  </inertial>
</link>

<wheel lr="left" tY="1"/>
<wheel lr="right" tY="-1"/>



<!-- Robot's arm -->

<servo ln="link0" x="0.0" y="0.0" z="0.0" />

<servo ln="link1" x="0.0" y="0.0" z="0.0" />

<link name="link2">
	<visual>
	  <origin rpy="0.00 0.00 0.00" xyz="${-0.090/2+0.01} 0.0 ${-servoWidth/2}"/>
	  <geometry>
	    <box size="0.090  0.010 0.001" />
	  </geometry>
	  <material name="red"/>
	</visual>
	<visual>
	  <origin rpy="0.00 0.00 0.00" xyz="${-0.090/2+0.01} 0.00 ${servoWidth/2}"/>
	  <geometry>
	    <box size="0.090 0.010 0.001" />
	  </geometry>
	  <material name="red"/>
	</visual>
	<inertial>
	  <mass value="0.05"/>
	  <inertia ixx="0.04" ixy="0.00" ixz="0.00" iyy="0.04" iyz="0.00" izz="0.02"/>
	</inertial>
</link>


<servo ln="link3" x="${-servoLength/2+0.01}" y="0.0" z="0.0" />

<link name="link4">
	<visual>
		<origin rpy="0.00 0.00 0.00" xyz="${-0.090/2+0.01} 0.0 ${-servoWidth/2}"/>
		<geometry>
			<box size="0.090  0.010 0.001" />
		</geometry>
		<material name="red"/>
	</visual>
	<visual>
		<origin rpy="0.00 0.00 0.00" xyz="${-0.090/2+0.01} 0.00 ${servoWidth/2}"/>
		<geometry>
			<box size="0.090 0.010 0.001" />
		</geometry>
		<material name="red"/>
	</visual>
	<inertial>
		<mass value="0.05"/>
		<inertia ixx="0.04" ixy="0.00" ixz="0.00" iyy="0.04" iyz="0.00" izz="0.02"/>
	</inertial>
</link>

<servo ln="link5" x="${-servoLength/2+0.01}" y="0.0" z="0.0" />

<link name="finger">
	<visual>
		<origin rpy="0 ${PI/2} 0 " xyz="${-servoLength+0.01} 0.0 0.0 "/>
		<geometry>
			<cylinder radius="${fingerRadius}" length="${fingerLength}"/>
		</geometry>
	</visual>
	<collision>
		<origin rpy="0 ${PI/2} 0 " xyz="${-servoLength+0.01} 0.0 0.0 "/>
		<geometry>
			<cylinder radius="${fingerRadius}" length="${fingerLength}"/>
		</geometry>
	</collision>
	<inertial>
		<origin rpy="0 ${PI/2} 0 " xyz="${-servoLength+0.01} 0.0 0.0 "/>
		<mass value="${fingerWeight}"/>
		<cylinder_inertia m="${fingerWeight}" r="${fingerRadius}" h="${fingerLength}" />
	</inertial>
</link>

<joint name="chassis_arm" type="fixed">
	<parent link="chassis"/>
	<child link="link0"/>
	<origin xyz="0.00 0.00 ${chassisHeight/2+wheelRadius+servoWidth/2}" rpy="0 0 0" />
</joint>

<joint name="link0_joint" type="revolute">
	<parent link="link0"/>
	<child link="link1"/>
	<origin xyz="${servoLength/2-0.010} 0.0 ${servoWidth/2+servoHeight/2+servoAxisLength}" rpy="${-PI/2} 0.0 0.0" />
	<axis xyz="0.0 1.0 0.0" />
	<limit effort="30" velocity="1.0" lower="${-PI/2}" upper="${PI/2}" />
</joint>

<joint name="link1_joint" type="revolute">
	<parent link="link1"/>
	<child link="link2"/>
	<origin xyz="${servoLength/2-0.01} 0.0 0.0" rpy="0.0 0.0 0.0" />
	<axis xyz="0.0 0.0 1.00" />
	<limit effort="30" velocity="1.0" lower="${-PI/2}" upper="${PI/2}" />
</joint>

<joint name="link3_joint" type="revolute">
	<parent link="link2"/>
	<child link="link3"/>
	<origin xyz="${-0.090+2*0.01} 0.0 0.00" rpy="0 0 0" />
	<axis xyz="0.0 0.00 1.00" />
	<limit effort="30" velocity="1.0" lower="${-PI/2}" upper="${PI/2}" />
</joint>

<joint name="link4_joint" type="fixed">
	<parent link="link3"/>
	<child link="link4"/>
	<origin xyz="${-servoLength+2*0.01} 0.0 0.00" rpy="0 0 0" />
</joint>

<joint name="link5_joint" type="revolute">
	<parent link="link4"/>
	<child link="link5"/>
	<origin xyz="${-0.090+2*0.01} 0.0 0.00" rpy="0 0 0" />
	<axis xyz="0.0 0.00 1.00" />
	<limit effort="30" velocity="1.0" lower="${-PI/2}" upper="${PI/2}" />
</joint>

<joint name="link6_joint" type="fixed">
	<parent link="link5"/>
	<child link="camera"/>
	<origin xyz="-0.01 ${-servoHeight/2-cameraSize/2} 0.0" rpy="${PI/2} ${PI} 0.0" />
</joint>

<joint name="link7_joint" type="fixed">
	<parent link="link5"/>
	<child link="finger"/>
	<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
</joint>


<!-- ========================== -->
<!--          CAMERAS           -->
<!-- ========================== -->

<link name="camera">
  <collision>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
    <geometry>
      <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
    </geometry>
  </collision>

  <visual>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
    <geometry>
      <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
    </geometry>
    <material name="blue"/>
  </visual>

  <inertial>
    <mass value="${cameraMass}" />
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <box_inertia m="${cameraMass}" x="${cameraSize}" y="${cameraSize}" z="${cameraSize}" />
  </inertial>
</link>


<!-- ========================= -->
<!--           LIDAR           -->
<!-- ========================= -->

<joint name="chassis_lidar" type="fixed">
  <parent link="chassis"/>
  <child link="rplidar_base"/>
  <origin xyz="0.1 0 ${chassisHeight/2+wheelRadius+.05867/2}" rpy="0 0 0" />
</joint>

<link name="rplidar_base">
	<collision>
		<origin xyz="0 0 0" rpy="0 0 0" />
		<geometry>
			<cylinder radius="0.04267" length=".05867" />
		</geometry>
	</collision>
	<visual>
		<origin xyz="0 0 0" rpy="0 0 0" />
		<geometry>
			<cylinder radius="0.04267" length=".05867" />
		</geometry>
	</visual>
	<inertial>
		<mass value="0.01" />
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<cylinder_inertia m="0.01" r="0.04267" h=".05867" />
	</inertial>
</link>


<joint name="rplidar_base_top" type="revolute" >
	<parent link="rplidar_base" />
	<child link="rplidar_top" />
	<origin xyz="0.0 0.0 ${0.05867/2}" rpy="0 0 0" />
	<axis xyz="0.0 0.0 1.0" />
	<limit effort="30" velocity="1.0" lower="${-PI}" upper="${PI}" />
	<dynamics damping="1.0" friction="100.0"/>
</joint>


<link name="rplidar_top">
    <collision>
      	<origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <cylinder radius="0.04267" length="0.07357" />
        </geometry>
    </collision>
    <visual>
 	<origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <cylinder radius="0.04267" length="0.07357" />
        </geometry>
    </visual>
		<inertial>
		<mass value="0.01" />
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<cylinder_inertia m="0.100" r="0.04267" h="0.07357" />
	</inertial>
</link>

<!-- The RPLIDAR is controlled in order for the TF to be published (otherwise Rviz will indicate an error.  -->
<transmission name="rplidar">
	<type>transmission_interface/SimpleTransmission</type>
	<joint name="rplidar_base_top">
		<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
	</joint>
	<actuator name="rplidar_motor">
		<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		<mechanicalReduction>1</mechanicalReduction>
	</actuator>
</transmission>

</robot>
